#!/usr/bin/env python3
"""
Generate reference plots for the three implemented signal families:
- clean
- noise
- spikes

The plots are derived from the same formulas and parameters used in firmware,
but generated offline so they remain reproducible even when a live DUT capture
is blocked by USB instability.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from generate_signal_family_plots import (
    ensure_dir,
    plot_adaptive_fs,
    plot_spectrum,
    plot_waveform,
)


FFT_N = 256
BASE_FS_HZ = 100.0
NOISE_SIGMA = 0.2
SPIKE_PROB = 0.02
SPIKE_MIN = 5.0
SPIKE_MAX = 15.0


def generate_clean(t_seconds: np.ndarray) -> np.ndarray:
    return 2.0 * np.sin(2.0 * np.pi * 3.0 * t_seconds) + 4.0 * np.sin(2.0 * np.pi * 5.0 * t_seconds)


def clamp_adaptive_fs(dominant_hz: float) -> float:
    proposed = round((dominant_hz * 8.0) / 5.0) * 5.0
    return float(min(50.0, max(20.0, proposed)))


def major_peak(samples: np.ndarray, fs_hz: float) -> float:
    window = np.hamming(len(samples))
    spectrum = np.fft.rfft(samples * window)
    freqs = np.fft.rfftfreq(len(samples), d=1.0 / fs_hz)
    mags = np.abs(spectrum)
    if len(mags) <= 1:
        return 0.0
    return float(freqs[np.argmax(mags[1:]) + 1])


def build_signal_windows(signal_name: str, window_count: int) -> list[np.ndarray]:
    rng = np.random.default_rng(20260423)
    total_samples = FFT_N * window_count
    t_seconds = np.arange(total_samples, dtype=float) / BASE_FS_HZ
    clean = generate_clean(t_seconds)

    if signal_name == "clean":
        values = clean
    elif signal_name == "noise":
        values = clean + rng.normal(0.0, NOISE_SIGMA, size=total_samples)
    elif signal_name == "spikes":
        values = clean + rng.normal(0.0, NOISE_SIGMA, size=total_samples)
        spike_mask = rng.random(total_samples) < SPIKE_PROB
        spike_amp = rng.uniform(SPIKE_MIN, SPIKE_MAX, size=total_samples)
        spike_sign = rng.choice(np.array([-1.0, 1.0]), size=total_samples)
        values = values + spike_mask * spike_amp * spike_sign
    else:
        raise ValueError(f"unsupported signal family: {signal_name}")

    return [values[i * FFT_N : (i + 1) * FFT_N] for i in range(window_count)]


def build_fft_rows(windows: list[np.ndarray]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for window in windows:
        dominant_hz = major_peak(window, BASE_FS_HZ)
        rows.append(
            {
                "dominant_hz": f"{dominant_hz:.6f}",
                "fs_hz": f"{clamp_adaptive_fs(dominant_hz):.6f}",
            }
        )
    return rows


def write_reference_summary(
    path: Path,
    signal_name: str,
    waveform_meta: dict[str, str],
    spectrum_meta: dict[str, str],
    adaptive_meta: dict[str, str],
) -> None:
    lines = [
        f"# {signal_name} Signal Plot Summary",
        "",
        f"- Waveform window: seq `{waveform_meta['seq']}`, `fs={waveform_meta['fs_hz']} Hz`, `n={waveform_meta['samples']}`",
        f"- Signal amplitude range: `{waveform_meta['y_min']}` to `{waveform_meta['y_max']}`",
        f"- Dominant spectral peaks: `{spectrum_meta['peak_1_hz']} Hz`, `{spectrum_meta['peak_2_hz']} Hz`, `{spectrum_meta['peak_3_hz']} Hz`",
        f"- Adaptive fs mean/min/max: `{adaptive_meta['fs_mean_hz']} / {adaptive_meta['fs_min_hz']} / {adaptive_meta['fs_max_hz']} Hz`",
        f"- Dominant frequency mean: `{adaptive_meta['dominant_mean_hz']} Hz` across `{adaptive_meta['fft_updates']}` FFT updates",
        "",
        "Generated by `tools/generate_bonus_signal_reference_plots.py` from the implemented firmware signal definitions.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate reference plots for clean/noise/spikes signal families")
    parser.add_argument(
        "--output-dir",
        default="source/results/20260423_signal_family_plots",
        help="Directory where the signal-family plot bundle will be written",
    )
    parser.add_argument(
        "--window-count",
        type=int,
        default=6,
        help="How many FFT windows to synthesize per signal for the adaptive-fs history",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir).resolve()
    ensure_dir(output_dir)

    summary_lines = [
        "# Signal Family Reference Plots",
        "",
        "These plots are generated from the implemented firmware signal definitions:",
        "- `clean`: `2*sin(2*pi*3*t) + 4*sin(2*pi*5*t)`",
        f"- `noise`: clean signal + Gaussian noise with `sigma={NOISE_SIGMA}`",
        f"- `spikes`: noise signal + signed uniform spike injection in `+-U({SPIKE_MIN:.0f}, {SPIKE_MAX:.0f})` with `p={SPIKE_PROB * 100:.0f}%`",
        "",
        f"Sampling assumptions for the reference plots: `FFT_N={FFT_N}`, baseline `fs={BASE_FS_HZ:.0f} Hz`, `{args.window_count}` synthetic FFT windows per signal.",
        "Adaptive policy: `dominant_hz * 8`, rounded to `5 Hz` steps and clamped to `20-50 Hz`.",
        "",
    ]

    for signal_name in ("clean", "noise", "spikes"):
        signal_dir = output_dir / signal_name
        ensure_dir(signal_dir)

        windows = build_signal_windows(signal_name, args.window_count)
        first_window = windows[0]
        t = np.arange(len(first_window), dtype=float) / BASE_FS_HZ
        fft_rows = build_fft_rows(windows)

        waveform_meta = plot_waveform(
            signal_dir / f"{signal_name}_waveform.svg",
            signal_name,
            1,
            BASE_FS_HZ,
            t,
            first_window,
        )
        spectrum_meta = plot_spectrum(
            signal_dir / f"{signal_name}_spectrum.svg",
            signal_name,
            1,
            BASE_FS_HZ,
            first_window,
        )
        adaptive_meta = plot_adaptive_fs(
            signal_dir / f"{signal_name}_adaptive_fs.svg",
            signal_name,
            fft_rows,
        )
        write_reference_summary(
            signal_dir / f"{signal_name}_summary.md",
            signal_name,
            waveform_meta,
            spectrum_meta,
            adaptive_meta,
        )

        summary_lines.extend(
            [
                f"## {signal_name}",
                "",
                f"- Dominant mean frequency: `{adaptive_meta['dominant_mean_hz']} Hz`",
                f"- Adaptive fs mean/min/max: `{adaptive_meta['fs_mean_hz']} / {adaptive_meta['fs_min_hz']} / {adaptive_meta['fs_max_hz']} Hz`",
                f"- Main spectrum peaks: `{spectrum_meta['peak_1_hz']} Hz`, `{spectrum_meta['peak_2_hz']} Hz`, `{spectrum_meta['peak_3_hz']} Hz`",
                f"- Plots: `{signal_name}_waveform.svg`, `{signal_name}_spectrum.svg`, `{signal_name}_adaptive_fs.svg`",
                "",
            ]
        )

    (output_dir / "SUMMARY.md").write_text("\n".join(summary_lines) + "\n", encoding="utf-8")
    print(f"[bonus-signal-plots] wrote bundle to {output_dir}")


if __name__ == "__main__":
    main()
