#!/usr/bin/env python3
"""
Capture one DUT plotting session from serial logs and passive MQTT subscriptions.

This script creates a timestamped session folder under tools/plot_sessions/ and
stores both raw and parsed data for later figure generation.

Expected firmware: one of the *_plot_capture PlatformIO environments so the
serial stream includes [PLOT] / [PLOT-SAMPLES] lines in addition to the normal
[FFT], [AGG], [MQTT], and [LATENCY] logs.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import threading
import time
from datetime import datetime
from pathlib import Path

import paho.mqtt.client as mqtt
import serial

TOPIC_AVG = "eri/iot/average"
TOPIC_PONG = "eri/iot/pong"

RE_FFT = re.compile(
    r"\[FFT\]\s+dominant = ([\d.]+) Hz\s+→\s+fs updated to ([\d.]+) Hz"
)
RE_AGG = re.compile(
    r"\[AGG\].*win=(\d+).*mean=([+\-\d.]+).*n=(\d+).*fs=([\d.]+).*proc_us=(\d+)"
)
RE_LATENCY = re.compile(r"\[LATENCY\].*rtt_ms=(\d+)")
RE_LORA = re.compile(
    r"\[LoRa\]\s+uplink #(\d+)\s+mean=([+\-\d.]+)\s+encoded=(-?\d+)\s+"
    r"cumulative=(\d+) B\s+vs_oversampled=(\d+) B\s+ratio=([\d.]+)x\s+e2e_latency=(\d+) ms"
)
RE_MQTT = re.compile(
    r"\[MQTT\]\s+#(\d+)\s+avg=([+\-\d.]+)\s+payload=(\d+) B\s+total=(\d+) B\s+baseline=(\d+) B\s+ratio=([\d.]+)x"
)
RE_PLOT_HEADER = re.compile(
    r"\[PLOT\]\s+type=fft_window\s+seq=(\d+)\s+fs=([\d.]+)\s+n=(\d+)"
)
RE_PLOT_SAMPLES = re.compile(r"\[PLOT-SAMPLES\]\s+seq=(\d+)\s+values=(.+)")


def iso_now() -> str:
    return datetime.now().astimezone().isoformat(timespec="milliseconds")


class SessionCapture:
    def __init__(self, session_dir: Path, args: argparse.Namespace) -> None:
        self.session_dir = session_dir
        self.args = args
        self.stop_event = threading.Event()
        self.window_count = 0
        self.start_window: int | None = None
        self.lock = threading.Lock()
        self.pending_plot_headers: dict[int, dict[str, float | int]] = {}

        self.raw_serial = open(session_dir / "serial.log", "a", encoding="utf-8", buffering=1)

        self.fft_writer, self.fft_file = self._open_csv(
            "fft.csv",
            ["iso_time", "dominant_hz", "fs_hz"],
        )
        self.agg_writer, self.agg_file = self._open_csv(
            "agg.csv",
            ["iso_time", "window", "mean", "sample_count", "fs_hz", "proc_us"],
        )
        self.latency_writer, self.latency_file = self._open_csv(
            "latency.csv",
            ["iso_time", "rtt_ms"],
        )
        self.mqtt_send_writer, self.mqtt_send_file = self._open_csv(
            "mqtt_send.csv",
            [
                "iso_time",
                "message_index",
                "avg",
                "payload_bytes",
                "total_bytes",
                "baseline_bytes",
                "ratio_x",
            ],
        )
        self.mqtt_rx_writer, self.mqtt_rx_file = self._open_csv(
            "mqtt_rx.csv",
            ["iso_time", "topic", "payload"],
        )
        self.lora_writer, self.lora_file = self._open_csv(
            "lora.csv",
            [
                "iso_time",
                "uplink_index",
                "mean",
                "encoded",
                "cumulative_bytes",
                "oversampled_bytes",
                "ratio_x",
                "e2e_latency_ms",
            ],
        )
        self.plot_writer, self.plot_file = self._open_csv(
            "plot_samples.csv",
            ["iso_time", "seq", "fs_hz", "sample_index", "t_seconds", "value"],
        )

    def _open_csv(self, name: str, header: list[str]) -> tuple[csv.writer, object]:
        path = self.session_dir / name
        f = open(path, "w", newline="", encoding="utf-8")
        writer = csv.writer(f)
        writer.writerow(header)
        return writer, f

    def write_metadata(self) -> None:
        payload = {
            "created_at": iso_now(),
            "serial_port": self.args.port,
            "baud": self.args.baud,
            "broker_host": self.args.broker_host,
            "broker_port": self.args.broker_port,
            "duration_s": self.args.duration,
            "max_windows": self.args.max_windows,
            "notes": "Generated by tools/plot_capture.py",
        }
        (self.session_dir / "metadata.json").write_text(
            json.dumps(payload, indent=2),
            encoding="utf-8",
        )

    def close(self) -> None:
        for f in [
            self.raw_serial,
            self.fft_file,
            self.agg_file,
            self.latency_file,
            self.mqtt_send_file,
            self.mqtt_rx_file,
            self.lora_file,
            self.plot_file,
        ]:
            f.close()

    def handle_serial_line(self, line: str) -> None:
        stamp = iso_now()
        self.raw_serial.write(f"{stamp} {line}\n")

        if m := RE_FFT.search(line):
            self.fft_writer.writerow([stamp, m.group(1), m.group(2)])
            return

        if m := RE_AGG.search(line):
            current_window = int(m.group(1))
            self.agg_writer.writerow(
                [stamp, m.group(1), m.group(2), m.group(3), m.group(4), m.group(5)]
            )
            with self.lock:
                if self.start_window is None:
                    self.start_window = current_window
                self.window_count = current_window
            return

        if m := RE_LATENCY.search(line):
            self.latency_writer.writerow([stamp, m.group(1)])
            return

        if m := RE_LORA.search(line):
            self.lora_writer.writerow(
                [
                    stamp,
                    m.group(1),
                    m.group(2),
                    m.group(3),
                    m.group(4),
                    m.group(5),
                    m.group(6),
                    m.group(7),
                ]
            )
            return

        if m := RE_MQTT.search(line):
            self.mqtt_send_writer.writerow(
                [
                    stamp,
                    m.group(1),
                    m.group(2),
                    m.group(3),
                    m.group(4),
                    m.group(5),
                    m.group(6),
                ]
            )
            return

        if m := RE_PLOT_HEADER.search(line):
            seq = int(m.group(1))
            self.pending_plot_headers[seq] = {
                "fs_hz": float(m.group(2)),
                "sample_count": int(m.group(3)),
            }
            return

        if m := RE_PLOT_SAMPLES.search(line):
            seq = int(m.group(1))
            meta = self.pending_plot_headers.get(seq)
            if not meta:
                return

            fs_hz = float(meta["fs_hz"])
            values = [chunk.strip() for chunk in m.group(2).split(",") if chunk.strip()]
            for idx, raw_value in enumerate(values):
                t_seconds = idx / fs_hz if fs_hz > 0 else 0.0
                self.plot_writer.writerow(
                    [stamp, seq, f"{fs_hz:.6f}", idx, f"{t_seconds:.6f}", raw_value]
                )
            return

    def serial_worker(self) -> None:
        ser = serial.Serial(self.args.port, self.args.baud, timeout=1)
        try:
            while not self.stop_event.is_set():
                raw = ser.readline()
                if not raw:
                    continue
                line = raw.decode("utf-8", errors="replace").strip()
                if line:
                    self.handle_serial_line(line)
        finally:
            ser.close()

    def mqtt_worker(self) -> None:
        def on_connect(client, _userdata, _flags, reason_code, _properties):
            if reason_code.is_failure:
                print(f"[capture] MQTT connect failed: {reason_code}")
                return
            client.subscribe(TOPIC_AVG)
            client.subscribe(TOPIC_PONG)

        def on_message(_client, _userdata, msg):
            payload = msg.payload.decode("utf-8", errors="replace").strip()
            self.mqtt_rx_writer.writerow([iso_now(), msg.topic, payload])

        client = mqtt.Client(
            callback_api_version=mqtt.CallbackAPIVersion.VERSION2,
            client_id="eri-plot-capture",
            clean_session=True,
        )
        client.on_connect = on_connect
        client.on_message = on_message
        client.connect(self.args.broker_host, self.args.broker_port, keepalive=60)
        client.loop_start()
        try:
            while not self.stop_event.is_set():
                time.sleep(0.2)
        finally:
            client.loop_stop()
            client.disconnect()

    def should_stop(self, started_at: float) -> bool:
        if self.args.duration and (time.monotonic() - started_at) >= self.args.duration:
            return True
        if self.args.max_windows is not None:
            with self.lock:
                if self.start_window is not None:
                    if (self.window_count - self.start_window + 1) >= self.args.max_windows:
                        return True
                elif self.window_count >= self.args.max_windows:
                    return True
        return False


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Capture one DUT plotting session")
    parser.add_argument("--port", required=True, help="Serial port, e.g. /dev/ttyUSB0")
    parser.add_argument("--baud", type=int, default=115200)
    parser.add_argument("--broker-host", default="127.0.0.1")
    parser.add_argument("--broker-port", type=int, default=1883)
    parser.add_argument("--duration", type=float, default=0.0, help="Stop after N seconds")
    parser.add_argument(
        "--max-windows",
        type=int,
        default=None,
        help="Stop after this many [AGG] windows",
    )
    parser.add_argument(
        "--session-name",
        default="",
        help="Optional readable suffix for the created session folder",
    )
    return parser.parse_args()


def build_session_dir(args: argparse.Namespace) -> Path:
    root = Path(__file__).resolve().parent / "plot_sessions"
    root.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    suffix = ""
    if args.session_name:
        safe = re.sub(r"[^a-zA-Z0-9_-]+", "-", args.session_name.strip()).strip("-")
        if safe:
            suffix = f"_{safe}"
    session_dir = root / f"{stamp}{suffix}"
    session_dir.mkdir()
    return session_dir


def main() -> None:
    args = parse_args()
    session_dir = build_session_dir(args)
    capture = SessionCapture(session_dir, args)
    capture.write_metadata()

    serial_thread = threading.Thread(target=capture.serial_worker, daemon=True)
    mqtt_thread = threading.Thread(target=capture.mqtt_worker, daemon=True)

    print(f"[capture] Session directory: {session_dir}")
    print("[capture] Waiting for serial + MQTT data. Press Ctrl-C to stop.")

    started_at = time.monotonic()
    serial_thread.start()
    mqtt_thread.start()

    try:
        while not capture.should_stop(started_at):
            time.sleep(0.2)
    except KeyboardInterrupt:
        pass
    finally:
        capture.stop_event.set()
        serial_thread.join(timeout=2)
        mqtt_thread.join(timeout=2)
        capture.close()

    print(f"[capture] Finished. Parsed files saved under {session_dir}")


if __name__ == "__main__":
    main()
